name: win
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
        - run: chcp 65001
        - name: Check out
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version: 3.19.0
        - name: pip install flet
          run: pip install flet==0.25.1
        - name: Run
          run: flet build windows